### ISSUE TITLE
Tree.js error, can't edit my pages

### ISSUE THREAD

**Issue by fourroses666** [WorkForFood/MODxPress#10]
When I click on the navigation buttons in the tree nothing happens.
In console I see an error:

tree.js line 259
parent.main.location.href="index.php?a="+window.globalVars.treeActionHref+"&id=" + id; // edit as default action

![error-console](https://cloud.githubusercontent.com/assets/523389/13847219/5e5e7a26-ec4c-11e5-962f-b8ceffae330d.jpg)

**Comment by fourroses666** [comment]
Full console issues:

![full-console](https://cloud.githubusercontent.com/assets/523389/13847331/fe446ff0-ec4c-11e5-982f-870f92b812de.jpg)

**Comment by WorkForFood** [comment]
Hello. Ok i'll check it.
Just tell me what plugins do you use for admin side. What your operation system and which version of FF do you use.

It's seem like your browser can't get vars from global window context or window.globalVars is not defined on tree frame. Can you also check is globalVars defined on tree frame. It's look like window.globalVars = { somevars defined here }

Thank you for bug report.

**Comment by Deesen** [comment]
I think it is because of ' which should be escaped to \' ?

**Comment by Deesen** [comment]
@fourroses666 I tested with "nederlands-utf8" and it works with this fix.

**Comment by fourroses666** [comment]
Oh missed this. Need to check!

**Comment by fourroses666** [comment]
Now it works! Good find :)
