### ISSUE TITLE
ошибка Warning: array_key_exists() expects parameter 2 to be array, null given in MODxPress/includes/render.class.inc.php on line 19

### ISSUE THREAD

**Issue by Dmi3yy** [WorkForFood/MODxPress#5]
http://take.ms/Awt40

**Comment by WorkForFood** [comment]
Странно. Посмотрю в чем проблема.

**Comment by Dmi3yy** [comment]
может потому что нет ни одной папки )

## 

Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80

четверг, 25 февраля 2016 г. в 14:29, WorkForFood написал:

**Comment by WorkForFood** [comment]
А блин. Так это же варнинг) Там второй параметр не определен вот и ругается.

**Comment by WorkForFood** [comment]
Определил переменную в конструкторе. Больше варнингов нет.
